export const Action_Type = {
  LOGIN_REQUEST:"LOGIN_REQUEST",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAILURE:"LOGIN_FAILURE",
  GET_REQUEST:"GET_REQUEST",
  GET_SUCCESS:"GET_SUCCESS",
  GET_FAILURE:"GET_FAILURE",
}