export const Action_Type = {
  LOGIN_REQUEST:"LOGIN_REQUEST",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAILURE:"LOGIN_FAILURE",
  LOGOUT:"LOGOUT",
  GET_REQUEST:"GET_REQUEST",
  GET_SUCCESS:"GET_SUCCESS",
  GET_FAILURE:"GET_FAILURE",
  ADD_TO_CART:"ADD_TO_CART",
  REMOVE_CART:"REMOVE_CART"
}