export const ACTION_TYPE = {
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    GET_PRODUCTS_REQUEST:"GET_PRODUCTS_REQUEST",
    GET_PRODUCTS_SUCCESS:"GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_FAILURE:"GET_PRODUCTS_FAILURE",
    ADD_PRODUCTS:"ADD_PRODUCTS",
    UPDATE_PRODUCTS:"UPDATE_PRODUCTS",
}